---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-postgres
  template:
    metadata:
      labels:
        app: cat-postgres
    spec:
      containers:
        - image: "bitnami/postgresql:latest"
          imagePullPolicy: IfNotPresent
          name: cat-postgres
          env:
            - name: POSTGRESQL_USERNAME
              value: bk
            - name: POSTGRESQL_DATABASE
              value: bk
            - name: POSTGRESQL_PASSWORD
              value: bk
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: cat-postgres
  labels:
    app: cat-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  #      nodePort: 31070
  selector:
    app: cat-postgres
