apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/configmap.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
namespace: prod
namePrefix: prod-
patchesStrategicMerge:
  - patch-env.yaml
#  - patch-memorylimit.yaml
commonLabels:
  env: prod
